<?php 
    $infosUser = new Zend_Session_Namespace('Zend_Auth');
    $breadcrumb = "<a href='".$this->url(
                                    array('controller' => 'Location',
                                          'action'     => 'index')) . "'>Locations en cours</a> | "
                 ."<label>Historique des locations</label>";
    if (isset($infosUser->user)) {
        if ($infosUser->role == "Employé") {
            $breadcrumb = "<a href='".$this->url(
                                            array('controller' => 'Location',
                                                  'action'     => 'ajouter'), "", true)."'>Saisir une location</a> | "
                         .$breadcrumb ;
        }
    }
    
    $this->layout()->breadcrumb = $breadcrumb ;
    
    $this->layout()->titre = "Historique des locations terminés ".(($this->personne != null)? "pour $this->personne" : "") ;
?>
<?php if ($this->personne!= null): ?>
<label class="label">Liste des films que <?php echo $this->personne ?> a loué :</label>
<?php endif ?>
<table cellpadding="0" cellspacing="0">
    <thead>
        <?php if  ($infosUser->role == 'Employé'): ?>
        <th>Client</th>
        <?php endif; ?>
        <th>Film</th>
        <th>Type</th>
        <th>N° Media</th>
        <th>Date emprunt</th>
        <th>Date retour</th>
    </thead>
    <tbody>
        
        <?php if (count($this->locations)>0): ?>
            <?php foreach ($this->locations as $location): ?>
                <tr>
                    <?php if ($infosUser->role == 'Employé'): ?>
                        <td>
                            <a class='loupe' 
                               title='Consulter la fiche location'
                               href='<?php echo $this->url(
                                                array("controller" => "Location",
                                                      "action"     => "consulter",
                                                      "idLocation" => $location->getId()), "", true) ?>'>
                            </a>
                            <?php echo htmlentities($location->getPersonne()->getIdentite()) ?>
                        </td>
                    <?php endif; ?>
                    <td>
                        <a class='loupe' 
                            title='Consulter la fiche du film'
                            href='<?php echo $this->url(
                                             array("controller" => "Film",
                                                   "action"     => "consulter",
                                                   "idFilm"     => $location->getMedia()->getFilm()->getId()), "", true) ?>'>
                        </a>
                        <?php echo htmlentities($location->getMedia()->getFilm()->getNom()) ?>
                    </td>
                    <td>
                        <?php echo htmlentities($location->getMedia()->getType()) ?>
                    </td>
                    <td>
                        <?php echo htmlentities($location->getMedia()->getNumero()) ?>
                    </td>
                    <td>
                        <?php echo $location->getDateLocation()->format("d/m/y") ?>
                    </td>
                    <td>
                        <?php echo $location->getDateRetour()->format("d/m/y") ?>
                    </td>
                  </tr>
            <?php endforeach; ?>        
        <?php endif; ?>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
        $("table").dataTable({
            "bJQueryUI": true,
            "sPaginationType": "two_button"
        });
    }) ;
</script>