<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Personne extends \Entities\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function verifierPassword($password)
    {
        $this->__load();
        return parent::verifierPassword($password);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getIdentite()
    {
        $this->__load();
        return parent::getIdentite();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getCourriel()
    {
        $this->__load();
        return parent::getCourriel();
    }

    public function getAdresse1()
    {
        $this->__load();
        return parent::getAdresse1();
    }

    public function getAdresse2()
    {
        $this->__load();
        return parent::getAdresse2();
    }

    public function getCodePostal()
    {
        $this->__load();
        return parent::getCodePostal();
    }

    public function getVille()
    {
        $this->__load();
        return parent::getVille();
    }

    public function getEstActif()
    {
        $this->__load();
        return parent::getEstActif();
    }

    public function getEstEmploye()
    {
        $this->__load();
        return parent::getEstEmploye();
    }

    public function getDateCreation()
    {
        $this->__load();
        return parent::getDateCreation();
    }

    public function getNumeroAdherent()
    {
        $this->__load();
        return parent::getNumeroAdherent();
    }

    public function getListeLocation()
    {
        $this->__load();
        return parent::getListeLocation();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function setCourriel($courriel)
    {
        $this->__load();
        return parent::setCourriel($courriel);
    }

    public function setAdresse1($adresse1 = NULL)
    {
        $this->__load();
        return parent::setAdresse1($adresse1);
    }

    public function setAdresse2($adresse2 = NULL)
    {
        $this->__load();
        return parent::setAdresse2($adresse2);
    }

    public function setCodePostal($codePostal)
    {
        $this->__load();
        return parent::setCodePostal($codePostal);
    }

    public function setVille($ville)
    {
        $this->__load();
        return parent::setVille($ville);
    }

    public function setEstActif($estActif)
    {
        $this->__load();
        return parent::setEstActif($estActif);
    }

    public function setEstEmploye($estEmploye)
    {
        $this->__load();
        return parent::setEstEmploye($estEmploye);
    }

    public function setDateCreation($dateCreation)
    {
        $this->__load();
        return parent::setDateCreation($dateCreation);
    }

    public function setNumeroAdherent($numeroAdherent)
    {
        $this->__load();
        return parent::setNumeroAdherent($numeroAdherent);
    }

    public function setListeLocation($listeLocation)
    {
        $this->__load();
        return parent::setListeLocation($listeLocation);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'prenom', 'nom', 'password', 'courriel', 'adresse1', 'adresse2', 'codePostal', 'ville', 'estActif', 'estEmploye', 'dateCreation', 'numeroAdherent', 'listeLocation');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}