<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Film extends \Entities\Film implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function estDisponible()
    {
        $this->__load();
        return parent::estDisponible();
    }

    public function existeUnMediaActif()
    {
        $this->__load();
        return parent::existeUnMediaActif();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function getDateFilm()
    {
        $this->__load();
        return parent::getDateFilm();
    }

    public function getResume()
    {
        $this->__load();
        return parent::getResume();
    }

    public function getDateCreation()
    {
        $this->__load();
        return parent::getDateCreation();
    }

    public function getListeMedia()
    {
        $this->__load();
        return parent::getListeMedia();
    }

    public function getRealisateur()
    {
        $this->__load();
        return parent::getRealisateur();
    }

    public function getActeur1()
    {
        $this->__load();
        return parent::getActeur1();
    }

    public function getActeur2()
    {
        $this->__load();
        return parent::getActeur2();
    }

    public function getActeur3()
    {
        $this->__load();
        return parent::getActeur3();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function setDateFilm($dateFilm)
    {
        $this->__load();
        return parent::setDateFilm($dateFilm);
    }

    public function setResume($resume)
    {
        $this->__load();
        return parent::setResume($resume);
    }

    public function setDateCreation($dateCreation)
    {
        $this->__load();
        return parent::setDateCreation($dateCreation);
    }

    public function setListeMedia($listeMedia)
    {
        $this->__load();
        return parent::setListeMedia($listeMedia);
    }

    public function setRealisateur(\Entities\ActeurRealisateur $realisateur)
    {
        $this->__load();
        return parent::setRealisateur($realisateur);
    }

    public function setActeur1(\Entities\ActeurRealisateur $acteur1)
    {
        $this->__load();
        return parent::setActeur1($acteur1);
    }

    public function setActeur2(\Entities\ActeurRealisateur $acteur2 = NULL)
    {
        $this->__load();
        return parent::setActeur2($acteur2);
    }

    public function setActeur3(\Entities\ActeurRealisateur $acteur3 = NULL)
    {
        $this->__load();
        return parent::setActeur3($acteur3);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'dateFilm', 'resume', 'dateCreation', 'listeMedia', 'realisateur', 'acteur1', 'acteur2', 'acteur3');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}